apiVersion: apps/v1
kind: Deployment
metadata:
  name: apex-analyticsapp
  namespace: apex-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyticsapp
  template:
    metadata:
      labels:
        app: analyticsapp
    spec:
      containers:
      - name: analyticsapp
        image: registry.marcel.im/atosanalyticsapp
        ports:
        - containerPort: 3838
---
apiVersion: v1
kind: Service
metadata:
  name: apex-entrypoint
  namespace: apex-demo
spec:
  type: NodePort
  selector:
    app: analyticsapp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 3838